/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TempMsg'
 * message type.
 */

public class TempMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 20;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new TempMsg of size 20. */
    public TempMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TempMsg of the given data_length. */
    public TempMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg with the given data_length
     * and base offset.
     */
    public TempMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg using the given byte array
     * as backing store.
     */
    public TempMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TempMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TempMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg embedded in the given message
     * at the given base offset.
     */
    public TempMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TempMsg embedded in the given message
     * at the given base offset and length.
     */
    public TempMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TempMsg> \n";
      try {
        s += "  [temperature=";
        for (int i = 0; i < 5; i++) {
          s += "0x"+Long.toHexString(getElement_temperature(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [timestamp=";
        for (int i = 0; i < 5; i++) {
          s += "0x"+Long.toHexString(getElement_timestamp(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temperature
    //   Field type: short[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temperature' is signed (false).
     */
    public static boolean isSigned_temperature() {
        return false;
    }

    /**
     * Return whether the field 'temperature' is an array (true).
     */
    public static boolean isArray_temperature() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'temperature'
     */
    public static int offset_temperature(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temperature'
     */
    public static int offsetBits_temperature(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'temperature' as a short[]
     */
    public short[] get_temperature() {
        short[] tmp = new short[5];
        for (int index0 = 0; index0 < numElements_temperature(0); index0++) {
            tmp[index0] = getElement_temperature(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'temperature' from the given short[]
     */
    public void set_temperature(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_temperature(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'temperature'
     */
    public short getElement_temperature(int index1) {
        return (short)getSIntBEElement(offsetBits_temperature(index1), 16);
    }

    /**
     * Set an element of the array 'temperature'
     */
    public void setElement_temperature(int index1, short value) {
        setSIntBEElement(offsetBits_temperature(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'temperature'
     */
    public static int totalSize_temperature() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'temperature'
     */
    public static int totalSizeBits_temperature() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'temperature'
     */
    public static int elementSize_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'temperature'
     */
    public static int elementSizeBits_temperature() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'temperature'
     */
    public static int numDimensions_temperature() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'temperature'
     */
    public static int numElements_temperature() {
        return 5;
    }

    /**
     * Return the number of elements in the array 'temperature'
     * for the given dimension.
     */
    public static int numElements_temperature(int dimension) {
      int array_dims[] = { 5,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: timestamp
    //   Field type: int[], unsigned
    //   Offset (bits): 80
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'timestamp' is signed (false).
     */
    public static boolean isSigned_timestamp() {
        return false;
    }

    /**
     * Return whether the field 'timestamp' is an array (true).
     */
    public static boolean isArray_timestamp() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'timestamp'
     */
    public static int offset_timestamp(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'timestamp'
     */
    public static int offsetBits_timestamp(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'timestamp' as a int[]
     */
    public int[] get_timestamp() {
        int[] tmp = new int[5];
        for (int index0 = 0; index0 < numElements_timestamp(0); index0++) {
            tmp[index0] = getElement_timestamp(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'timestamp' from the given int[]
     */
    public void set_timestamp(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_timestamp(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'timestamp'
     */
    public int getElement_timestamp(int index1) {
        return (int)getUIntBEElement(offsetBits_timestamp(index1), 16);
    }

    /**
     * Set an element of the array 'timestamp'
     */
    public void setElement_timestamp(int index1, int value) {
        setUIntBEElement(offsetBits_timestamp(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'timestamp'
     */
    public static int totalSize_timestamp() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'timestamp'
     */
    public static int totalSizeBits_timestamp() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'timestamp'
     */
    public static int elementSize_timestamp() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'timestamp'
     */
    public static int elementSizeBits_timestamp() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'timestamp'
     */
    public static int numDimensions_timestamp() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'timestamp'
     */
    public static int numElements_timestamp() {
        return 5;
    }

    /**
     * Return the number of elements in the array 'timestamp'
     * for the given dimension.
     */
    public static int numElements_timestamp(int dimension) {
      int array_dims[] = { 5,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
