/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'EventMsg'
 * message type.
 */

public class EventMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new EventMsg of size 3. */
    public EventMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new EventMsg of the given data_length. */
    public EventMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg with the given data_length
     * and base offset.
     */
    public EventMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg using the given byte array
     * as backing store.
     */
    public EventMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public EventMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public EventMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg embedded in the given message
     * at the given base offset.
     */
    public EventMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new EventMsg embedded in the given message
     * at the given base offset and length.
     */
    public EventMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <EventMsg> \n";
      try {
        s += "  [srcAddr=0x"+Long.toHexString(get_srcAddr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [moteEvent=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_moteEvent(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [prob=";
        for (int i = 0; i < 1; i++) {
          s += "0x"+Long.toHexString(getElement_prob(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: srcAddr
    //   Field type: byte, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'srcAddr' is signed (false).
     */
    public static boolean isSigned_srcAddr() {
        return false;
    }

    /**
     * Return whether the field 'srcAddr' is an array (false).
     */
    public static boolean isArray_srcAddr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'srcAddr'
     */
    public static int offset_srcAddr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'srcAddr'
     */
    public static int offsetBits_srcAddr() {
        return 0;
    }

    /**
     * Return the value (as a byte) of the field 'srcAddr'
     */
    public byte get_srcAddr() {
        return (byte)getSIntBEElement(offsetBits_srcAddr(), 8);
    }

    /**
     * Set the value of the field 'srcAddr'
     */
    public void set_srcAddr(byte value) {
        setSIntBEElement(offsetBits_srcAddr(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'srcAddr'
     */
    public static int size_srcAddr() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'srcAddr'
     */
    public static int sizeBits_srcAddr() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: moteEvent
    //   Field type: byte[], unsigned
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'moteEvent' is signed (false).
     */
    public static boolean isSigned_moteEvent() {
        return false;
    }

    /**
     * Return whether the field 'moteEvent' is an array (true).
     */
    public static boolean isArray_moteEvent() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'moteEvent'
     */
    public static int offset_moteEvent(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'moteEvent'
     */
    public static int offsetBits_moteEvent(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'moteEvent' as a byte[]
     */
    public byte[] get_moteEvent() {
        byte[] tmp = new byte[1];
        for (int index0 = 0; index0 < numElements_moteEvent(0); index0++) {
            tmp[index0] = getElement_moteEvent(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'moteEvent' from the given byte[]
     */
    public void set_moteEvent(byte[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_moteEvent(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a byte) of the array 'moteEvent'
     */
    public byte getElement_moteEvent(int index1) {
        return (byte)getSIntBEElement(offsetBits_moteEvent(index1), 8);
    }

    /**
     * Set an element of the array 'moteEvent'
     */
    public void setElement_moteEvent(int index1, byte value) {
        setSIntBEElement(offsetBits_moteEvent(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'moteEvent'
     */
    public static int totalSize_moteEvent() {
        return (8 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'moteEvent'
     */
    public static int totalSizeBits_moteEvent() {
        return 8;
    }

    /**
     * Return the size, in bytes, of each element of the array 'moteEvent'
     */
    public static int elementSize_moteEvent() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'moteEvent'
     */
    public static int elementSizeBits_moteEvent() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'moteEvent'
     */
    public static int numDimensions_moteEvent() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'moteEvent'
     */
    public static int numElements_moteEvent() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'moteEvent'
     * for the given dimension.
     */
    public static int numElements_moteEvent(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'moteEvent' with a String
     */
    public void setString_moteEvent(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_moteEvent(i, (byte)s.charAt(i));
         }
         setElement_moteEvent(i, (byte)0); //null terminate
    }

    /**
     * Read the array 'moteEvent' as a String
     */
    public String getString_moteEvent() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,1)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_moteEvent(i) == (char)0) break;
             carr[i] = (char)getElement_moteEvent(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: prob
    //   Field type: short[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'prob' is signed (false).
     */
    public static boolean isSigned_prob() {
        return false;
    }

    /**
     * Return whether the field 'prob' is an array (true).
     */
    public static boolean isArray_prob() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'prob'
     */
    public static int offset_prob(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'prob'
     */
    public static int offsetBits_prob(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 1) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'prob' as a short[]
     */
    public short[] get_prob() {
        short[] tmp = new short[1];
        for (int index0 = 0; index0 < numElements_prob(0); index0++) {
            tmp[index0] = getElement_prob(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'prob' from the given short[]
     */
    public void set_prob(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_prob(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'prob'
     */
    public short getElement_prob(int index1) {
        return (short)getUIntBEElement(offsetBits_prob(index1), 8);
    }

    /**
     * Set an element of the array 'prob'
     */
    public void setElement_prob(int index1, short value) {
        setUIntBEElement(offsetBits_prob(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'prob'
     */
    public static int totalSize_prob() {
        return (8 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'prob'
     */
    public static int totalSizeBits_prob() {
        return 8;
    }

    /**
     * Return the size, in bytes, of each element of the array 'prob'
     */
    public static int elementSize_prob() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'prob'
     */
    public static int elementSizeBits_prob() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'prob'
     */
    public static int numDimensions_prob() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'prob'
     */
    public static int numElements_prob() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'prob'
     * for the given dimension.
     */
    public static int numElements_prob(int dimension) {
      int array_dims[] = { 1,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'prob' with a String
     */
    public void setString_prob(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_prob(i, (short)s.charAt(i));
         }
         setElement_prob(i, (short)0); //null terminate
    }

    /**
     * Read the array 'prob' as a String
     */
    public String getString_prob() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,1)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_prob(i) == (char)0) break;
             carr[i] = (char)getElement_prob(i);
         }
         return new String(carr,0,i);
    }

}
